services:
  python:
    container_name: python
    build:
      context: .
    networks:
      - tokemo
    volumes:
      - ./app:/app
      - data-subject:/app/subject
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - data-db:/var/lib/postgresql/data
    networks:
      - tokemo
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - "5432:5432"
    command: >
      postgres -c max_wal_size=2GB -c checkpoint_completion_target=0.9

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    networks:
      - tokemo
    ports:
      - 8080:8080

networks:
  tokemo:
    driver: bridge

volumes:
  data-db:
    driver: local
    driver_opts:
      type: none
      device: ./data/db
      o: bind

  data-subject:
    driver: local
    driver_opts:
      type: none
      device: ./data/subject
      o: bind